import type { ButtonItem } from "@/types/types"

// بيانات الدروس
export const lessons: {
  lesson_one: ButtonItem[]
  lesson_two: ButtonItem[]
  lesson_three: ButtonItem[]
  lesson_four: ButtonItem[]
  lesson_five: ButtonItem[];
  lesson_six: ButtonItem[];
  lesson_seven: ButtonItem[];
  lesson_eight: ButtonItem[];
  lesson_nine: ButtonItem[];
  lesson_ten: ButtonItem[];
  lesson_eleven: ButtonItem[];
  lesson_twelve: ButtonItem[];
  lesson_thirteen: ButtonItem[];
  lesson_fourteen: ButtonItem[];
  lesson_fifteen: ButtonItem[];
  lesson_sixteen: ButtonItem[];
} = {
  lesson_one: [
    { type: "button", id: "1vid0", text: "Goals", icon: "video", time: "" },
    { type: "button", id: "1vid1", text: "Vocabulary", icon: "video" },
    { type: "button", id: "1act1", text: "Activity", icon: "activity" },
    { type: "button", id: "1vid2", text: "Self-Introduction ", icon: "video" },
    { type: "button", id: "1act2", text: "Activity", icon: "activity" },
    { type: "button", id: "1act3", text: "Guided Self-Introduction", icon: "activity" },
    { type: "button", id: "1vid3", text: "Scientific Opinion", icon: "video" },
    { type: "button", id: "1act4", text: "Activity", icon: "activity" },
    { type: "button", id: "1act5", text: "Activity", icon: "activity" },
    { type: "button", id: "1act6", text: "Guided Self-Evaluation", icon: "activity" },
    { type: "button", id: "1act7", text: "Feedback", icon: "activity" },
    { type: "button", id: "1act8", text: "assignment", icon: "quiz" },
    ],
  lesson_two: [
    { type: "button", id: "2vid0", text: "Goals", icon: "video" },
    { type: "button", id: "2vid1", text: "Giving presentations confidently in English", icon: "video" },
    { type: "button", id: "2act1", text: "Activity - Presentation Language", icon: "activity" },
    { type: "button", id: "2vid2", text: "The Water Cycle", icon: "video" },
    { type: "button", id: "2vid3", text: "DNA Structure", icon: "video" },
    { type: "button", id: "2act2", text: "TASK", icon: "activity" },
    { type: "button", id: "2act3", text: "TASK", icon: "activity" },
    { type: "button", id: "2act4", text: "TASK", icon: "activity" },
    { type: "button", id: "2act5", text: "Science Elevator Pitch in Pairs", icon: "activity" },
    { type: "button", id: "2vid4", text: "Clarifying Scientific Ideas", icon: "video" },
    { type: "button", id: "2act6", text: "TASK", icon: "activity" },
    { type: "button", id: "2act7", text: "Guided Reflection", icon: "activity" },
    { type: "button", id: "2act8", text: "Mini Presentation Challenge", icon: "activity" },
  ],
  lesson_three: [
    { type: "button", id: "3vid0", text: "Goals", icon: "video" },
    { type: "button", id: "3vid1", text: "Academic Discussion", icon: "video" },
    { type: "button", id: "3vid2", text: "Mini-Dialogue", icon: "video" },
    { type: "button", id: "3act1", text: "Task", icon: "activity" },
    { type: "button", id: "3vid3", text: "Summarizing techniques", icon: "video" },
    { type: "button", id: "3act2", text: "Example of a Summary Technique", icon: "activity" },
    { type: "button", id: "3act3", text: "Task", icon: "activity" },
    { type: "button", id: "3act4", text: "Taking a Stand", icon: "activity" },
    { type: "button", id: "3act5", text: "Replay and Reflect", icon: "activity" },
    { type: "button", id: "3act6", text: "Summarizing techniques", icon: "activity" },
  ],
  lesson_four: [
    { type: "button", id: "4vid0", text: "Goals", icon: "video" },
    { type: "button", id: "4vid1", text: "Interruption Chain", icon: "video" },
    { type: "button", id: "4vid2", text: "Sample Opening Statement", icon: "video" },
    { type: "button", id: "4act1", text: "Introducing a New Topic", icon: "activity" },
    { type: "button", id: "4act2", text: "Task", icon: "activity" },
    { type: "button", id: "4act3", text: "Task", icon: "activity" },
    { type: "button", id: "4act4", text: "Support Your Claim", icon: "activity" },
    { type: "button", id: "4vid3", text: "Roundtable Discussion", icon: "video" },
    { type: "button", id: "4act5", text: "Task", icon: "activity" },
    { type: "button", id: "4act6", text: "Rubric Check", icon: "activity" },
    { type: "button", id: "4act7", text: "Summative Assessment", icon: "activity" },
  ],
  lesson_five: [
    { type: "button", id: "5vid0", text: "Goals", icon: "video" },
    { type: "button", id: "5act1", text: "Vocabulary Warm-up", icon: "activity" },
    { type: "button", id: "5act2", text: "Listening Strategies Game", icon: "activity" },
    { type: "button", id: "5act3", text: "Task", icon: "activity" },
    { type: "button", id: "5act4", text: "Task", icon: "activity" },
    { type: "button", id: "5act5", text: "Task", icon: "activity" },
    { type: "button", id: "5vid1", text: "Group Discussion", icon: "video" },
    { type: "button", id: "5vid2", text: "Key Point Extraction", icon: "video" },
    { type: "button", id: "5vid3", text: "Reflection and Feedback", icon: "video" },
    { type: "button", id: "5act6", text: "Task", icon: "activity" },
    { type: "button", id: "5act7", text: "Accent & Tone Analysis1", icon: "activity" },
    { type: "button", id: "5act8", text: "Accent & Tone Analysis2", icon: "activity" },
    { type: "button", id: "5act9", text: "Accent & Tone Analysis3", icon: "activity" },
    { type: "button", id: "5act10", text: "Accent & Tone Analysis4", icon: "activity" },
    { type: "button", id: "5act11", text: "TED Talk", icon: "activity" },
    { type: "button", id: "5act12", text: "Self-Evaluation", icon: "activity" },
    { type: "button", id: "5act13", text: "Summative Assessment", icon: "activity" },
  ], 
  lesson_six: [
    { type: "button", id: "6vid0", text: "Goals", icon: "video" },
    { type: "button", id: "6act1", text: "Pre-Task Stage", icon: "activity" },
    { type: "button", id: "6act2", text: "Vocabulary Checkpoint", icon: "activity" },
    { type: "button", id: "6vid1", text: "The Cornell Method", icon: "video" },
    { type: "button", id: "6vid2", text: "The Outline Method", icon: "video" },
    { type: "button", id: "6act3", text: "Task", icon: "activity" },
    { type: "button", id: "6act4", text: "Task", icon: "activity" },
    { type: "button", id: "6act5", text: "Reconstruct the Procedure", icon: "activity" },
    { type: "button", id: "6act6", text: "Task", icon: "activity" },
    { type: "button", id: "6act7", text: "Present & Explain", icon: "activity" },
    { type: "button", id: "6act8", text: "Evaluation", icon: "activity" },
    { type: "button", id: "6act9", text: "Summative Assessment", icon: "activity" },
  ],
  lesson_seven: [
    { type: "button", id: "7vid0", text: "Goals", icon: "video" },
    { type: "button", id: "7vid1", text: "Tone Match Game", icon: "video" },
    { type: "button", id: "7vid2", text: "Activity", icon: "video" },
        { type: "button", id: "7act1", text: "Task", icon: "activity" },
    { type: "button", id: "7vid3", text: "Vocabulary in Emotion", icon: "video" },
    { type: "button", id: "7vid4", text: "Activity", icon: "video" },
        { type: "button", id: "7act2", text: "Paraphrasing Worksheet", icon: "activity" },
    { type: "button", id: "7act3", text: "TASK", icon: "activity" },
    { type: "button", id: "7vid5", text: "Fact vs. Opinion Sort ", icon: "video" },
        { type: "button", id: "7act4", text: "Task", icon: "activity" },
    { type: "button", id: "7act5", text: "Task", icon: "activity" },
    { type: "button", id: "7vid6", text: "Intent And Tone", icon: "video" },
    { type: "button", id: "7vid7", text: "Tone Reinforces or Contradicts", icon: "video" },
    { type: "button", id: "7vid8", text: "Activity", icon: "video" },
    { type: "button", id: "7vid9", text: "Role-play Debate", icon: "video" },
    { type: "button", id: "7act6", text: "TASK", icon: "activity" },
    { type: "button", id: "7act7", text: "TASK", icon: "activity" },
    { type: "button", id: "7act8", text: "Summative Assessment", icon: "activity" },
  ], 
  lesson_eight: [
    { type: "button", id: "8vid0", text: "Goals", icon: "video" },
    { type: "button", id: "8vid1", text: "Academic discussions", icon: "video" },
    { type: "button", id: "8vid2", text: "Scientific debates", icon: "video" },
    { type: "button", id: "8vid3", text: "Predict the Argument", icon: "video" },
        { type: "button", id: "8act1", text: "Task", icon: "activity" },
    { type: "button", id: "8vid4", text: "Common Guide Inference Strategies", icon: "video" },
        { type: "button", id: "8act2", text: "Clipped Dialogue", icon: "activity" },
    { type: "button", id: "8act3", text: "Vocabulary Match", icon: "activity" },
    { type: "button", id: "8act4", text: "Role-play Usage", icon: "activity" },
    { type: "button", id: "8act5", text: "TASK", icon: "activity" },
    { type: "button", id: "8vid5", text: "Following a structured argument flow", icon: "video" },
        { type: "button", id: "8act6", text: "Task", icon: "activity" },
    { type: "button", id: "8act7", text: "Guided Listening Debate Sheet", icon: "activity" },
    { type: "button", id: "8vid6", text: "Practice Mini-Debate", icon: "video" },
    { type: "button", id: "8act8", text: "Task", icon: "activity" },
    { type: "button", id: "8act9", text: "Feedback", icon: "activity" },
    { type: "button", id: "8act10", text: "Summative Assessment", icon: "activity" },
  ], 
  lesson_nine: [
    { type: "button", id: "9vid0", text: "Goals", icon: "video" },
    { type: "button", id: "9vid1", text: "Parts of a Scientific Article", icon: "video" },
    { type: "button", id: "9act1", text: "TASK", icon: "activity" },
    { type: "button", id: "9act2", text: "Vocabulary Scavenger Hunt", icon: "activity" },
    { type: "button", id: "9vid2", text: "Academic Texts", icon: "video" },
    { type: "button", id: "9act3", text: "Task", icon: "activity" },
    { type: "button", id: "9act4", text: "Task", icon: "activity" },
    { type: "button", id: "9act5", text: "Task", icon: "activity" },
    { type: "button", id: "9act6", text: "Task", icon: "activity" },
    { type: "button", id: "9vid3", text: "Chart & Graph Interpretation", icon: "video" },
    { type: "button", id: "9act7", text: "Analyze the chart", icon: "activity" },
    { type: "button", id: "9act8", text: "Strategy Circle Reflection", icon: "activity" },
    { type: "button", id: "9act9", text: "Summative Assessment", icon: "activity" },
  ], 
  lesson_ten: [
    { type: "button", id: "10vid0", text: "Goals", icon: "video" },
    { type: "button", id: "10vid1", text: "Academic Writing", icon: "video" },
        { type: "button", id: "10act1", text: "Sentence Breakdown Challenge", icon: "activity" },
    { type: "button", id: "10act2", text: "Context Clue Vocabulary Hunt", icon: "activity" },
    { type: "button", id: "10vid2", text: "Mini-Article", icon: "video" },
        { type: "button", id: "10act3", text: "Task", icon: "activity" },
    { type: "button", id: "10vid3", text: "author's intent", icon: "video" },
    { type: "button", id: "10vid4", text: "factual claims and assumptions", icon: "video" },
        { type: "button", id: "10act4", text: "TASK", icon: "activity" },
    { type: "button", id: "10vid5", text: "Workshop", icon: "video" },
    { type: "button", id: "10vid6", text: "Model for evaluate claims critically", icon: "video" },
    { type: "button", id: "10act5", text: "Task", icon: "activity" },
    { type: "button", id: "10act6", text: "Summary Swap", icon: "activity" },
    { type: "button", id: "10act7", text: "Evaluation", icon: "activity" },
    { type: "button", id: "10act8", text: "Summative Assessment", icon: "activity" },
  ], 
  lesson_eleven: [
    { type: "button", id: "11vid0", text: "Goals", icon: "video" },
    { type: "button", id: "11vid1", text: "Concept of Efficient Reading", icon: "video" },
        { type: "button", id: "11act1", text: "Reading Habits", icon: "activity" },
    { type: "button", id: "11act2", text: "Structure Scavenger Hunt", icon: "activity" },
    { type: "button", id: "11vid2", text: "Strategy Mapping", icon: "video" },
        { type: "button", id: "11act3", text: "TASK", icon: "activity" },
    { type: "button", id: "11act4", text: "Guided Reading & Highlighting", icon: "activity" },
    { type: "button", id: "11act5", text: "Guidance to compare", icon: "activity" },
    { type: "button", id: "11vid3", text: "Online Source Credibility Check", icon: "video" },
    { type: "button", id: "11act6", text: "Task", icon: "activity" },
    { type: "button", id: "11act7", text: "Summative Assessment", icon: "activity" },
  ], 
  lesson_twelve: [
    { type: "button", id: "12vid0", text: "Goals", icon: "video" },
        { type: "button", id: "12act1", text: "Source Sorting Game", icon: "activity" },
    { type: "button", id: "12act2", text: "Vocabulary Blitz", icon: "activity" },
    { type: "button", id: "12vid1", text: "The important five components", icon: "video" },
        { type: "button", id: "12act3", text: "Task", icon: "activity" },
    { type: "button", id: "12vid2", text: "The important five components", icon: "video" },
    { type: "button", id: "12vid3", text: "The Effect of Light on Plant Growth", icon: "video" },
    { type: "button", id: "12vid4", text: "Paraphrasing Challenge", icon: "video" },
    { type: "button", id: "12act4", text: "Task", icon: "activity" },
    { type: "button", id: "12act5", text: "Peer Review & Reflection", icon: "activity" },
    { type: "button", id: "12act6", text: "Summative Assessment", icon: "activity" },
  ],
lesson_thirteen: [
    { type: "button", id: "13vid0", text: "Goals", icon: "video" },
    { type: "button", id: "13vid1", text: "Components of a Scientific Report", icon: "video" },
        { type: "button", id: "13act1", text: "Scientific Report Puzzle", icon: "activity" },
    { type: "button", id: "13act2", text: "Task", icon: "activity" },
    { type: "button", id: "13vid2", text: "The Effect of pH on Enzyme Activity", icon: "video" },
        { type: "button", id: "13act3", text: "The Effect of pH on Enzyme Activity", icon: "activity" },
    { type: "button", id: "13act4", text: "TASK", icon: "activity" },
    { type: "button", id: "13vid3", text: "Drafting the Lab Report", icon: "video" },
    { type: "button", id: "13act5", text: "your notes", icon: "activity" },
    { type: "button", id: "13act6", text: "Scientific Report Evaluation Rubric", icon: "activity" },
    { type: "button", id: "13act7", text: "Evaluation", icon: "activity" },
    { type: "button", id: "13act8", text: "Summative Assessment", icon: "activity" },
], 
lesson_fourteen: [
    { type: "button", id: "14vid0", text: "Goals", icon: "video" },
    { type: "button", id: "14vid1", text: "Concept and Components of a Research Paper", icon: "video" },
        { type: "button", id: "14act1", text: "Research Paper Overview Discussion", icon: "activity" },
    { type: "button", id: "14act2", text: "Vocabulary Brainstorm", icon: "activity" },
    { type: "button", id: "14act3", text: "Paper Structure Walkthrough", icon: "activity" },
    { type: "button", id: "14vid2", text: "Research Paper", icon: "video" },
    { type: "button", id: "14act4", text: "Writing the Introduction", icon: "activity" },
    { type: "button", id: "14act5", text: "Writing the Body Paragraphs", icon: "activity" },
    { type: "button", id: "14act6", text: "Writing the Conclusion", icon: "activity" },
    { type: "button", id: "14act7", text: "Evaluation", icon: "activity" },
    { type: "button", id: "14act8", text: "Summative Assessment", icon: "activity" },
], 
lesson_fifteen: [
    { type: "button", id: "15vid0", text: "Goals", icon: "video" },
    { type: "button", id: "15vid1", text: "Key grammar rules", icon: "video" },
        { type: "button", id: "15act1", text: "TASK", icon: "activity" },
    { type: "button", id: "15vid2", text: "Data Presentation 1 ", icon: "video" },
    { type: "button", id: "15vid3", text: "Data Presentation 2 ", icon: "video" },
        { type: "button", id: "15act2", text: "Task", icon: "activity" },
    { type: "button", id: "15vid4", text: "Paraphrasing", icon: "video" },
    { type: "button", id: "15vid5", text: "plagiarism", icon: "video" },
    { type: "button", id: "15act3", text: "TASK", icon: "activity" },
    { type: "button", id: "15act4", text: "Grammar Exercise", icon: "activity" },
    { type: "button", id: "15act5", text: "Presenting Data ", icon: "activity" },
    { type: "button", id: "15act6", text: "Paraphrasing Practice", icon: "activity" },
    { type: "button", id: "15act7", text: "Feedback", icon: "activity" },
    { type: "button", id: "15act8", text: "Summative Assessment", icon: "activity" },
], 
lesson_sixteen: [
    { type: "button", id: "16vid0", text: "Goals", icon: "video" },
    { type: "button", id: "16vid1", text: "Common errors", icon: "video" },
    { type: "button", id: "16vid2", text: "Proofreading and editing strategies", icon: "video" },
        { type: "button", id: "16act1", text: "Task", icon: "activity" },
    { type: "button", id: "16vid3", text: "The basics of different citation styles", icon: "video" },
    { type: "button", id: "16vid4", text: "Abstract", icon: "video" },
        { type: "button", id: "16act2", text: "Task", icon: "activity" },
    { type: "button", id: "16act3", text: "Writing an Abstract", icon: "activity" },
    { type: "button", id: "16act4", text: "Proofreading Exercise", icon: "activity" },
    { type: "button", id: "16act5", text: "Citation Practice", icon: "activity" },
    { type: "button", id: "16vid5", text: "Authorized Sources", icon: "video" },
    { type: "button", id: "16act6", text: "Task", icon: "activity" },
    { type: "button", id: "16act7", text: "Evaluation", icon: "activity" },
    { type: "button", id: "16act8", text: "Summative Assessment", icon: "activity" },
],
}

// روابط الفيديوهات
export const videoMap: Record<string, string> = {
  "1vid0": "/videos/vid1/vid0.mp4",
  "1vid1": "/videos/vid1/vid1.mp4",
  "1vid2": "/videos/vid1/vid2.mp4",
  "1vid3": "/videos/vid1/vid3.mp4",
  "1vid4": "/videos/vid1/vid4.mp4",
  "1vid5": "/videos/vid1/vid5.mp4",
/*****************************************************************/
  "2vid0": "/videos/vid2/vid0.mp4",
  "2vid1": "/videos/vid2/vid1.mp4",
  "2vid2": "/videos/vid2/vid2.mp4",
  "2vid3": "/videos/vid2/vid3.mp4",
  "2vid4": "/videos/vid2/vid4.mp4",
/*****************************************************************/
  "3vid0": "/videos/vid3/vid0.mp4",
  "3vid1": "/videos/vid3/vid1.mp4",
  "3vid2": "/videos/vid3/vid2.mp4",
  "3vid3": "/videos/vid3/vid3.mp4",
/*****************************************************************/
  "4vid0": "/videos/vid4/vid0.mp4",
  "4vid1": "/videos/vid4/vid1.mp4",
  "4vid2": "/videos/vid4/vid2.mp4",
  "4vid3": "/videos/vid4/vid3.mp4",
/*****************************************************************/
  "5vid0": "/videos/vid5/vid0.mp4",
  "5vid1": "/videos/vid5/vid1.mp4",
  "5vid2": "/videos/vid5/vid2.mp4",
  "5vid3": "/videos/vid5/vid3.mp4",
/*****************************************************************/
  "6vid0": "/videos/vid6/vid0.mp4",
  "6vid1": "/videos/vid6/vid1.mp4",
  "6vid2": "/videos/vid6/vid2.mp4",
/*****************************************************************/
  "7vid0": "/videos/vid7/vid0.mp4",
  "7vid1": "/videos/vid7/vid1.mp4",
  "7vid2": "/videos/vid7/vid2.mp4",
  "7vid3": "/videos/vid7/vid3.mp4",
  "7vid4": "/videos/vid7/vid4.mp4",
  "7vid5": "/videos/vid7/vid5.mp4",
  "7vid6": "/videos/vid7/vid6.mp4",
  "7vid7": "/videos/vid7/vid7.mp4",
  "7vid8": "/videos/vid7/vid8.mp4",
  "7vid9": "/videos/vid7/vid9.mp4",
/*****************************************************************/
  "8vid0": "/videos/vid8/vid0.mp4",
  "8vid1": "/videos/vid8/vid1.mp4",
  "8vid2": "/videos/vid8/vid2.mp4",
  "8vid3": "/videos/vid8/vid3.mp4",
  "8vid4": "/videos/vid8/vid4.mp4",
  "8vid5": "/videos/vid8/vid5.mp4",
  "8vid6": "/videos/vid8/vid6.mp4",
/*****************************************************************/
  "9vid0": "/videos/vid9/vid0.mp4",
  "9vid1": "/videos/vid9/vid1.mp4",
  "9vid2": "/videos/vid9/vid2.mp4",
  "9vid3": "/videos/vid9/vid3.mp4",
/*****************************************************************/
  "10vid0": "/videos/vid10/vid0.mp4",
  "10vid1": "/videos/vid10/vid1.mp4",
  "10vid2": "/videos/vid10/vid2.mp4",
  "10vid3": "/videos/vid10/vid3.mp4",
  "10vid4": "/videos/vid10/vid4.mp4",
  "10vid5": "/videos/vid10/vid5.mp4",
  "10vid6": "/videos/vid10/vid6.mp4",
/*****************************************************************/
  "11vid0": "/videos/vid11/vid0.mp4",
  "11vid1": "/videos/vid11/vid1.mp4",
  "11vid2": "/videos/vid11/vid2.mp4",
  "11vid3": "/videos/vid11/vid3.mp4",
/*****************************************************************/
  "12vid0": "/videos/vid12/vid0.mp4",
  "12vid1": "/videos/vid12/vid1.mp4",
  "12vid2": "/videos/vid12/vid2.mp4",
  "12vid3": "/videos/vid12/vid3.mp4",
  "12vid4": "/videos/vid12/vid4.mp4",
/*****************************************************************/
  "13vid0": "/videos/vid13/vid0.mp4",
  "13vid1": "/videos/vid13/vid1.mp4",
  "13vid2": "/videos/vid13/vid2.mp4",
  "13vid3": "/videos/vid13/vid3.mp4",
/*****************************************************************/
  "14vid0": "/videos/vid14/vid0.mp4",
  "14vid1": "/videos/vid14/vid1.mp4",
  "14vid2": "/videos/vid14/vid2.mp4",
/*****************************************************************/
  "15vid0": "/videos/vid15/vid0.mp4",
  "15vid1": "/videos/vid15/vid1.mp4",
  "15vid2": "/videos/vid15/vid2.mp4",
  "15vid3": "/videos/vid15/vid3.mp4",
  "15vid4": "/videos/vid15/vid4.mp4",
  "15vid5": "/videos/vid15/vid5.mp4",
/*****************************************************************/
  "16vid0": "/videos/vid16/vid0.mp4",
  "16vid1": "/videos/vid16/vid1.mp4",
  "16vid2": "/videos/vid16/vid2.mp4",
  "16vid3": "/videos/vid16/vid3.mp4",
  "16vid4": "/videos/vid16/vid4.mp4",
  "16vid5": "/videos/vid16/vid5.mp4",
/*****************************************************************/
}

// روابط النماذج
export const formLinks: Record<string, string> = {
  "1act1": "https://forms.gle/QEFKLGgkzkK2nLdh7",
  "1act2": "https://forms.gle/MyfkTxeKw5cFoU6V6",
  "1act3": "https://forms.gle/yv9nSCzUvGG3mGC28",
  "1act4": "https://forms.gle/qZbA7RYmfpfwiKq49",
  "1act5": "https://forms.gle/WdmNTvop3ZKn1WaH8",
  "1act6": "https://forms.gle/GRWMSpgSMD6zhVEs9",
  "1act7": "https://forms.gle/xrCu5VDuvEnqoLv5A",
  "1act8": "https://forms.gle/pffcPuGr9zRdQ5U6A",
/*****************************************************************/
  "2act1": "https://forms.gle/7pFHGzh4YhHKxjGU7",
  "2act2": "https://forms.gle/5YxEQzmYUMbq4mn19 ",
  "2act3": " https://forms.gle/Czw3dfjuE7xygTQ19",
  "2act4": " https://forms.gle/sr9VFXXjDzEBWpaXA",
  "2act5": "https://forms.gle/PRgooTEFfMgjUSXT9 ",
  "2act6": "https://forms.gle/P3foRQTngH2Zdf3w8 ",
  "2act7": "https://forms.gle/DU7Hsb8vX7EbiJJs7 ",
  "2act8": "https://forms.gle/1dTxNUyWJjeJDx9Y9 ",
/*****************************************************************/
  "3act1": " https://forms.gle/zWk78Noq6ueiu8iH7",
  "3act2": "https://forms.gle/HfRaP6tRMkeBEcVw9 ",
  "3act3": "https://forms.gle/NncfZAeTnWixPDDh6 ",
  "3act4": "https://forms.gle/vFCaGQp5AJiaq8ZU9",
  "3act5": "https://forms.gle/1ezmAiesLACgk83s6 ",
  "3act6": "https://forms.gle/UJcQYTGxTbFCiswN7 ",
/*****************************************************************/
  "4act1": "https://forms.gle/vNijijt58iFg583D7 ",
  "4act2": "https://forms.gle/CVuf8akSBfKyVXYM9 ",
  "4act3": "https://forms.gle/MAnHPz4mDvmcqJdT9",
  "4act4": "https://forms.gle/3GLykxSfDCyjbzAR7",
  "4act5": "https://forms.gle/oxfxT8YmopFskBwq9 ",
  "4act6": " https://forms.gle/EzYQPBSf4KhQiFB57",
  "4act7": "https://forms.gle/o24YjcvcZ7LtkFLs9 ",
/*****************************************************************/
  "5act1": "https://forms.gle/CDn1YRKhPbZjM6bH9 ",
  "5act2": "https://forms.gle/jb98PMPaEWF2yrRJ7 ",
  "5act3": "https://forms.gle/g51ehUjhUSiMCcU18 ",
  "5act4": "https://forms.gle/sB6QJo9v5CjTN7ko7 ",
  "5act5": "https://forms.gle/KVKqSXRLJVjR8GLh7 ",
  "5act6": "https://forms.gle/yWVn5hYpNi3bkVR87 ",
  "5act7": "https://forms.gle/uQUYW7fj7ZKuyRx89 ",
  "5act8": "https://forms.gle/FnjdVWA9tJepRzFZ6 ",
  "5act9": "https://forms.gle/gR4JpYNZuMJv1dCt7 ",
  "5act10": "https://forms.gle/jomATaNqvcnMDMjN6 ",
  "5act11": "https://forms.gle/CiwPzyErjMRQHSbX9 ",
  "5act12": "https://forms.gle/2G4w73Wu9FuVty3dA ",
  "5act13": "https://forms.gle/X4XHCFA228csvCvL9 ",
/*****************************************************************/
  "6act1": "https://forms.gle/HH7tUXNfbLwAupN47 ",
  "6act2": "https://forms.gle/xCw5ZMHDUiEycS7m9 ",
  "6act3": "https://forms.gle/p7YUiHdTFWTRuZRe7 ",
  "6act4": "https://forms.gle/dZGfpdhwD9YrbKTC8",
  "6act5": "https://forms.gle/ZoLQ6T79Ez75kdsA7 ",
  "6act6": "https://forms.gle/2dwnKLNuacamUSEq8 ",
  "6act7": "https://forms.gle/STpVQQQ6TsyABUSP8 ",
  "6act8": "https://forms.gle/dQ9rB1UVLHLkJzkM7 ",
  "6act9": "https://forms.gle/rj6WfYQBSEmHUNJ78 ",
/*****************************************************************/
  "7act1": "https://forms.gle/vaensmWXabWiDD3C6 ",
  "7act2": "https://forms.gle/J2i2a16SfWM4VD1B7 ",
  "7act3": "https://forms.gle/dxHNEXPpEvyLZ1co6 ",
  "7act4": "https://forms.gle/f3R5Uhcd5Kniymbz6 ",
  "7act5": "https://forms.gle/oEDqRVuTWwRiCHF49 ",
  "7act6": "https://forms.gle/3b3LoezKgpjLSGCc9 ",
  "7act7": "https://forms.gle/M65g6FM2gscEwHty6 ",
  "7act8": " https://forms.gle/xKKtABYU1Ci4dgJf6",
/*****************************************************************/
  "8act1": "https://forms.gle/8FgiuaS4bcZMnhEVA ",
  "8act2": "https://forms.gle/E4LbH2vzAVWB4zfD7 ",
  "8act3": "https://forms.gle/bPSVUuDzu83GM5EG7 ",
  "8act4": "https://forms.gle/FAR9Hiee4ekLy4Zj9 ",
  "8act5": "https://forms.gle/RCciBNaH6c8SPVem9 ",
  "8act6": "https://forms.gle/Ps472dJASmf2NxEMA ",
  "8act7": "https://forms.gle/WtuxcqpuUcy1DW6B6 ",
  "8act8": "https://forms.gle/ydKEBCQdJ43EUyYc7 ",
  "8act9": "https://forms.gle/oq6dexuZujNRa1Bp9 ",
  "8act10": "https://forms.gle/rZAHydzw49V7HBBW6 ",
/*****************************************************************/
  "9act1": "https://forms.gle/4BABxS9r99afhicb9 ",
  "9act2": "https://forms.gle/n4DefBwX4HU6vUWE8 ",
  "9act3": "https://forms.gle/SDKCxZF58QQtxtKM9 ",
  "9act4": "https://forms.gle/XM2iYr6UWDHQqEEs5 ",
  "9act5": "https://forms.gle/zdtfNptz2amtSAE37 ",
  "9act6": "https://forms.gle/x4EqASUxYz6cBoJN8 ",
  "9act7": "https://forms.gle/7z43FQdDfrnTQMtc9 ",
  "9act8": " https://forms.gle/xVFVyrAZQjtAYuWZ7",
  "9act9": "https://forms.gle/mqqeDNm5SdGqYKjP9 ",
  /*****************************************************************/
  "10act1": "https://forms.gle/eoNYmQ5qRh8XZw1f6 ",
  "10act2": "https://forms.gle/2DHsMBXTxbwnQqmr6 ",
  "10act3": "https://forms.gle/afcUWpKhsUsESKAN6 ",
  "10act4": "https://forms.gle/gnSARwzo7fLbfSfu7 ",
  "10act5": "https://forms.gle/kgXrJHvb5GBhtNtc8 ",
  "10act6": "https://forms.gle/z6jvZC2ytPrmUhkh6 ",
  "10act7": "https://forms.gle/dggEQzxtyReMthHj6 ",
  "10act8": " https://forms.gle/dT9RgxYakyZR47Fu6",
/*****************************************************************/
  "11act1": "https://forms.gle/azb6Z2h8E8hCdvnH7 ",
  "11act2": "https://forms.gle/YHsZh7MRpZyfBeKh6 ",
  "11act3": "https://forms.gle/jBV3wkg84cfbgH2Q9 ",
  "11act4": "https://forms.gle/9WA3o3yeix9LyBE17 ",
  "11act5": "https://forms.gle/hfbk974Xw5mD8PCs5 ",
  "11act6": "https://forms.gle/puydkPwDUAFToxbVA ",
/*****************************************************************/
  "12act1": "https://forms.gle/jdMN51sXp6e4betu9 ",
  "12act2": " https://forms.gle/JPeN134sGTPSxpAA9",
  "12act3": "https://forms.gle/Lszy8qdFtqeU129k7 ",
  "12act4": "https://forms.gle/xX8hqzhKiyfXwfEy7 ",
  "12act5": "https://forms.gle/j4m4uz3a4jr9Ruup6 ",
  "12act6": "https://forms.gle/bP9vgcjKhuo7y7xaA ",
  /*****************************************************************/
  "13act1": " https://forms.gle/3gsJmduvyNDKJmJM7",
  "13act2": "https://forms.gle/BhK7HFY1pa378Pwi7 ",
  "13act3": " https://forms.gle/7sVaBg21cDwjiB48A",
  "13act4": "https://forms.gle/igfgfro3cDbmgASVA ",
  "13act5": "https://forms.gle/dz7zmfeeka3agWxD6 ",
  "13act6": "https://forms.gle/JXz7uSHKyXEfKBzL9 ",
  "13act7": " https://forms.gle/rzo6mhXiJcsQikAZ9",
  "13act8": "https://forms.gle/qFXDAiLNemM8Lhc3A ",
  /*****************************************************************/
  "14act1": "https://forms.gle/z9EJTpt7mMPPqbgk6 ",
  "14act2": "https://forms.gle/6dWqCX9S7wvbQuhD9 ",
  "14act3": "https://forms.gle/iFpbEs2StpnmN4Je7",
  "14act4": "https://forms.gle/KrDD78iFKxqjpCTdA ",
  "14act5": "https://forms.gle/1svDbMpaLFfxUh2C6 ",
  "14act6": "https://forms.gle/ahxD9yz8EfJSe9oV9 ",
  "14act7": " https://forms.gle/gvxG3Cqj1dU8h8Ka6",
  "14act8": " https://forms.gle/yRK2EwD1qhSYUBas6",
  /*****************************************************************/
  "15act1": "https://forms.gle/3fmQP9L5SKb9XCDD6 ",
  "15act2": "https://forms.gle/fVAJQRtvsDNiQqDbA ",
  "15act3": "https://forms.gle/MmUYdm9W5EwFT9NA7 ",
  "15act4": "https://forms.gle/aLFe5EG3RSnDXWzDA ",
  "15act5": "https://forms.gle/fAy1aGtV1AYT4REa6 ",
  "15act6": "https://forms.gle/qda3Mdx8ahPeRhkw6 ",
  "15act7": "https://forms.gle/X4Ceujm6ikH9qbSq9 ",
  "15act8": "https://forms.gle/J1nYYkjDmQqPVsgHA ",
  /*****************************************************************/
  "16act1": "https://forms.gle/B5XtFk1gLveaBpR67 ",
  "16act2": "https://forms.gle/ScfckLRvNN8y2zZN6 ",
  "16act3": "https://forms.gle/ByxWkw2ijJtAVGS47 ",
  "16act4": "https://forms.gle/JFCeSMWUUdXvssKH8 ",
  "16act5": "https://forms.gle/wbgrBsSQoN8S1pv9A ",
  "16act6": "https://forms.gle/eDjqDzSCzF9R8BJn7 ",
  "16act7": "https://forms.gle/mdPcQRjMBGgpXdpm7 ",
  "16act8": "https://forms.gle/AcS2yXEWPsx5fVxt5 ",
}
